services:
  wow-js-jail:
    image: ghcr.io/haruulzangi/2026-u18-private/wow-js-jail:latest
    networks: [traefik_proxy]
    restart: always
    environment:
      FLAG: ${FLAG:-HZU18{w0w_$1_you_w1n_$2}}
    read_only: true
    tmpfs:
      - /tmp
    mem_limit: 128m
    cpus: 0.5
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - traefik.http.routers.wow-js-jail-http.entrypoints=web
      - traefik.http.routers.wow-js-jail-http.rule=Host(`wow-js-jail.u18-2026.haruulzangi.mn`)
      - traefik.http.routers.wow-js-jail-http.middlewares=wow-js-jail-https
      - traefik.http.middlewares.wow-js-jail-https.redirectscheme.scheme=https
      - traefik.http.routers.wow-js-jail.entrypoints=websecure
      - traefik.http.routers.wow-js-jail.rule=Host(`wow-js-jail.u18-2026.haruulzangi.mn`)
      - traefik.http.services.wow-js-jail.loadbalancer.server.port=3000
      - traefik.http.routers.wow-js-jail.tls=true
      - traefik.http.routers.wow-js-jail.tls.certresolver=myresolver

networks:
  traefik_proxy:
    external: true